/// Flutter icons CotsumiIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CotsumiIcons
///      fonts:
///       - asset: fonts/CotsumiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CotsumiIcons {
  CotsumiIcons._();

  static const _kFontFam = 'CotsumiIcons';
  static const String? _kFontPkg = null;

  static const IconData check = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coinsuuicon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollicon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData genzaidakaicon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData osiraseicon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ribon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasseirirekiicon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
